"""
PRISM — compass/optimizer.py
DSPy Closed-Loop Workflow Optimizer

PRISM doesn't just measure. It learns and improves.

COMPASS uses VERDICT scores from live sessions to
automatically optimize the prompt architecture driving
AI agent behavior in a workflow.

If groundedness is declining  → rewrite retrieval prompt
If influence survival is low  → adjust uncertainty expression
If novelty delta is plateauing → push toward distant associations
If calibration is drifting    → tighten confidence language

Closed-loop. Evidence-driven. Client-specific.

This turns PRISM from an observability tool into a
self-improving deployment system.

The feature that signals you understand the full
FDE lifecycle — not just deployment, but continuous
improvement.
"""

from __future__ import annotations
import json
import hashlib
import numpy as np
from typing import List, Dict, Optional, Tuple, Any
from datetime import datetime
from dataclasses import dataclass, field
from enum import Enum

from core.eat.models import (
    EATEvent, AgentType, WorkflowSession
)


# ─── OPTIMIZATION SIGNAL ──────────────────────────────────────────────────────

class OptimizationSignal(str, Enum):
    GROUNDEDNESS       = "GROUNDEDNESS"
    CALIBRATION        = "CALIBRATION"
    INFLUENCE_SURVIVAL = "INFLUENCE_SURVIVAL"
    NOVELTY_DELTA      = "NOVELTY_DELTA"
    COMPOSITE          = "COMPOSITE"


# ─── PROMPT VARIANT ───────────────────────────────────────────────────────────

@dataclass
class PromptVariant:
    """
    A single prompt variant generated by COMPASS.
    Carries the prompt text, the signal it targets,
    and its performance history across sessions.
    """
    variant_id:       str
    agent_id:         str
    signal:           OptimizationSignal
    prompt_text:      str
    rationale:        str
    generation:       int       # Which optimization iteration produced this
    created_at:       datetime  = field(default_factory=datetime.utcnow)

    # Performance tracking
    sessions_run:     int       = 0
    score_history:    List[float] = field(default_factory=list)

    @property
    def mean_score(self) -> float:
        return float(np.mean(self.score_history)) if self.score_history else 0.0

    @property
    def score_trend(self) -> float:
        """Positive = improving, negative = declining."""
        if len(self.score_history) < 2:
            return 0.0
        return float(self.score_history[-1] - self.score_history[0])

    def record_score(self, score: float) -> None:
        self.score_history.append(score)
        self.sessions_run += 1

    def __repr__(self) -> str:
        return (
            f"PromptVariant({self.signal.value} | "
            f"gen={self.generation} | "
            f"score={self.mean_score:.3f} | "
            f"trend={self.score_trend:+.3f})"
        )


# ─── OPTIMIZATION RECORD ──────────────────────────────────────────────────────

@dataclass
class OptimizationRecord:
    """
    Records a single COMPASS optimization cycle.
    Tracks what triggered the optimization, what was changed,
    and whether it improved performance.
    """
    record_id:        str
    agent_id:         str
    session_id:       str
    signal:           OptimizationSignal
    trigger_score:    float           # Score that triggered optimization
    threshold:        float           # Threshold it fell below
    previous_prompt:  str
    new_prompt:       str
    rationale:        str
    generation:       int
    timestamp:        datetime = field(default_factory=datetime.utcnow)
    outcome_score:    Optional[float] = None  # Populated after next session
    improved:         Optional[bool]  = None


# ─── SIGNAL ANALYZER ──────────────────────────────────────────────────────────

class SignalAnalyzer:
    """
    Analyzes VERDICT scores from recent sessions to detect
    which optimization signals are degrading.
    """

    def __init__(
        self,
        groundedness_threshold:       float = 0.5,
        calibration_threshold:        float = 0.6,
        influence_survival_threshold: float = 0.5,
        novelty_threshold:            float = 0.3,
        window:                       int   = 3
    ):
        self.thresholds = {
            OptimizationSignal.GROUNDEDNESS:       groundedness_threshold,
            OptimizationSignal.CALIBRATION:        calibration_threshold,
            OptimizationSignal.INFLUENCE_SURVIVAL: influence_survival_threshold,
            OptimizationSignal.NOVELTY_DELTA:      novelty_threshold,
        }
        self.window = window

    def analyze(
        self,
        sessions: List[WorkflowSession]
    ) -> List[Tuple[OptimizationSignal, float, float]]:
        """
        Analyze recent sessions for degrading signals.

        Returns list of (signal, current_score, threshold)
        for signals that need optimization.
        """
        recent_sessions = sessions[-self.window:]
        degrading = []

        for signal, threshold in self.thresholds.items():
            score = self._mean_signal_score(recent_sessions, signal)
            if score is not None and score < threshold:
                degrading.append((signal, score, threshold))

        return degrading

    def _mean_signal_score(
        self,
        sessions: List[WorkflowSession],
        signal:   OptimizationSignal
    ) -> Optional[float]:
        """Extract mean signal score across sessions."""
        all_scores = []

        for session in sessions:
            for event in session.get_ai_events():
                if signal == OptimizationSignal.GROUNDEDNESS:
                    if event.groundedness is not None:
                        all_scores.append(event.groundedness)
                elif signal == OptimizationSignal.CALIBRATION:
                    if event.calibration_score is not None:
                        all_scores.append(event.calibration_score)
                elif signal == OptimizationSignal.INFLUENCE_SURVIVAL:
                    if event.influence_survival is not None:
                        all_scores.append(event.influence_survival)
                elif signal == OptimizationSignal.NOVELTY_DELTA:
                    if event.novelty_delta is not None:
                        all_scores.append(event.novelty_delta)

        return float(np.mean(all_scores)) if all_scores else None


# ─── PROMPT OPTIMIZER ─────────────────────────────────────────────────────────

class PromptOptimizer:
    """
    Core COMPASS prompt optimization engine.

    Generates improved prompt variants targeting specific
    degrading VERDICT signals.

    In production this calls the Anthropic API to generate
    prompt rewrites. For now it uses rule-based templates
    that encode the optimization logic — ready for LLM
    enhancement in the API layer.
    """

    # Optimization templates per signal
    TEMPLATES = {
        OptimizationSignal.GROUNDEDNESS: {
            "diagnosis": (
                "AI belief updates are not grounded in session evidence. "
                "The model is relying on pretraining knowledge rather than "
                "context provided in this workflow session."
            ),
            "instructions": [
                "Always cite specific evidence from the current session context "
                "before making any confidence update.",
                "If a hypothesis is not supported by evidence in the current "
                "session, explicitly state uncertainty rather than defaulting "
                "to pretraining knowledge.",
                "Before updating any belief, explicitly state: "
                "'Based on [evidence from session]...'",
                "Prioritize information provided by human agents in this session "
                "over general knowledge when they conflict.",
            ]
        },
        OptimizationSignal.CALIBRATION: {
            "diagnosis": (
                "AI confidence levels are not well-calibrated. "
                "High confidence statements are not being borne out "
                "by subsequent evidence."
            ),
            "instructions": [
                "Use explicit probability language: "
                "'I estimate 70% confidence that...' rather than 'clearly' or 'obviously'.",
                "When uncertain, express a range: "
                "'Between 40-60% likely, depending on...'",
                "Actively distinguish between high-confidence claims "
                "(direct evidence) and lower-confidence inferences (indirect).",
                "After each claim, rate your confidence: "
                "[HIGH/MEDIUM/LOW] and give the reason.",
            ]
        },
        OptimizationSignal.INFLUENCE_SURVIVAL: {
            "diagnosis": (
                "Human agents are not retaining AI-suggested belief updates. "
                "They accept AI suggestions initially but revert on reflection. "
                "AI influence is not surviving scrutiny."
            ),
            "instructions": [
                "When suggesting a belief update, provide the full reasoning chain "
                "so humans can evaluate the logic, not just the conclusion.",
                "Anticipate likely objections and address them proactively "
                "in your reasoning.",
                "Connect new suggestions to beliefs humans have already confirmed "
                "in this session to build on established common ground.",
                "Use conditional framing: 'If you accept X (which you confirmed "
                "earlier), then Y follows because...'",
            ]
        },
        OptimizationSignal.NOVELTY_DELTA: {
            "diagnosis": (
                "AI is introducing concepts already present in the human agents' "
                "conceptual graphs. No new concepts are being added to the ensemble. "
                "The AI is not expanding the collective conceptual frontier."
            ),
            "instructions": [
                "Before suggesting a concept, check whether it has already been "
                "discussed in this session. If so, look for adjacent unexplored concepts.",
                "Actively seek connections to domains not yet mentioned in the session: "
                "'From a [different domain] perspective, this connects to...'",
                "Introduce at least one concept from outside the current discussion "
                "frame in each response, with explicit justification.",
                "Use analogical reasoning to import concepts from distant fields: "
                "'This pattern resembles [concept from different domain] because...'",
            ]
        }
    }

    def generate_variant(
        self,
        agent_id:        str,
        signal:          OptimizationSignal,
        current_prompt:  str,
        trigger_score:   float,
        generation:      int
    ) -> PromptVariant:
        """
        Generate an optimized prompt variant targeting a specific signal.
        Combines the current prompt with targeted optimization instructions.
        """
        template = self.TEMPLATES.get(signal)
        if template is None:
            return PromptVariant(
                variant_id   = f"PV-{agent_id[:6]}-{generation}",
                agent_id     = agent_id,
                signal       = signal,
                prompt_text  = current_prompt,
                rationale    = "No template available for this signal.",
                generation   = generation
            )

        # Select optimization instructions based on severity
        severity_index = min(
            int((1.0 - trigger_score) * len(template["instructions"])),
            len(template["instructions"]) - 1
        )
        selected_instructions = template["instructions"][:severity_index + 1]

        # Build optimized prompt
        optimization_block = (
            f"\n\n[PRISM OPTIMIZATION — {signal.value}]\n"
            f"Diagnosis: {template['diagnosis']}\n"
            f"Instructions:\n" +
            "\n".join(f"  {i+1}. {inst}" for i, inst in enumerate(selected_instructions))
        )

        optimized_prompt = current_prompt.rstrip() + optimization_block

        rationale = (
            f"Signal {signal.value} degraded to {trigger_score:.3f} "
            f"(threshold: {self.TEMPLATES.get(signal, {}).get('threshold', 'N/A')}). "
            f"Applied {len(selected_instructions)} optimization instruction(s) "
            f"targeting {template['diagnosis'][:60]}..."
        )

        variant_id = hashlib.md5(
            f"{agent_id}-{signal.value}-{generation}".encode()
        ).hexdigest()[:12]

        return PromptVariant(
            variant_id  = f"PV-{variant_id}",
            agent_id    = agent_id,
            signal      = signal,
            prompt_text = optimized_prompt,
            rationale   = rationale,
            generation  = generation
        )


# ─── COMPASS OPTIMIZER ────────────────────────────────────────────────────────

class CompassOptimizer:
    """
    Main COMPASS optimization engine.

    Instantiated once per client deployment.
    Monitors VERDICT scores across sessions.
    Generates and tracks prompt variants.
    Selects the best-performing variant per agent.
    """

    def __init__(
        self,
        client_id:   str,
        workflow_id: str
    ):
        self.client_id   = client_id
        self.workflow_id = workflow_id

        self.analyzer  = SignalAnalyzer()
        self.optimizer = PromptOptimizer()

        # agent_id → current prompt
        self.current_prompts: Dict[str, str] = {}

        # agent_id → list of variants
        self.variants: Dict[str, List[PromptVariant]] = {}

        # All optimization records
        self.records: List[OptimizationRecord] = []

        # Session history for trend analysis
        self.session_history: List[WorkflowSession] = []

        self.generation = 0

    def register_agent(self, agent_id: str, initial_prompt: str) -> None:
        """Register an AI agent with its initial prompt."""
        self.current_prompts[agent_id] = initial_prompt
        self.variants[agent_id] = []

    def add_session(self, session: WorkflowSession) -> List[OptimizationRecord]:
        """
        Add a completed session to COMPASS.
        Analyzes for degrading signals and generates
        optimized prompt variants if needed.

        Returns list of optimization records created this cycle.
        """
        self.session_history.append(session)
        new_records = []

        # Need at least 2 sessions to detect trends
        if len(self.session_history) < 2:
            return new_records

        self.generation += 1
        degrading = self.analyzer.analyze(self.session_history)

        for signal, current_score, threshold in degrading:
            # Find AI agents in this session
            for agent_id in session.ai_agents:
                if agent_id not in self.current_prompts:
                    self.current_prompts[agent_id] = (
                        "You are a helpful AI assistant in a collaborative workflow."
                    )

                current_prompt = self.current_prompts[agent_id]

                # Generate optimized variant
                variant = self.optimizer.generate_variant(
                    agent_id       = agent_id,
                    signal         = signal,
                    current_prompt = current_prompt,
                    trigger_score  = current_score,
                    generation     = self.generation
                )

                self.variants.setdefault(agent_id, []).append(variant)

                # Record the optimization
                record = OptimizationRecord(
                    record_id      = f"OR-{self.generation}-{agent_id[:6]}",
                    agent_id       = agent_id,
                    session_id     = session.session_id,
                    signal         = signal,
                    trigger_score  = current_score,
                    threshold      = threshold,
                    previous_prompt = current_prompt,
                    new_prompt     = variant.prompt_text,
                    rationale      = variant.rationale,
                    generation     = self.generation
                )
                self.records.append(record)
                new_records.append(record)

                # Update current prompt
                self.current_prompts[agent_id] = variant.prompt_text

        return new_records

    def best_prompt(self, agent_id: str) -> str:
        """
        Return the best-performing prompt for an agent.
        Falls back to current prompt if no performance data.
        """
        agent_variants = self.variants.get(agent_id, [])
        scored = [v for v in agent_variants if v.sessions_run > 0]

        if not scored:
            return self.current_prompts.get(agent_id, "")

        return max(scored, key=lambda v: v.mean_score).prompt_text

    def optimization_summary(self) -> Dict:
        """
        Full optimization history for CHRONICLE reports.
        """
        total_variants   = sum(len(v) for v in self.variants.values())
        total_records    = len(self.records)
        signals_hit = {}
        for record in self.records:
            signals_hit[record.signal.value] = (
                signals_hit.get(record.signal.value, 0) + 1
            )

        return {
            "client_id":          self.client_id,
            "workflow_id":        self.workflow_id,
            "total_sessions":     len(self.session_history),
            "optimization_cycles": self.generation,
            "total_variants":     total_variants,
            "total_records":      total_records,
            "signals_optimized":  signals_hit,
            "agents_optimized":   list(self.current_prompts.keys()),
            "recent_records": [
                {
                    "record_id":     r.record_id,
                    "signal":        r.signal.value,
                    "trigger_score": round(r.trigger_score, 4),
                    "threshold":     round(r.threshold, 4),
                    "generation":    r.generation,
                    "rationale":     r.rationale[:100] + "..."
                }
                for r in self.records[-5:]
            ]
        }